apiVersion: v1
kind: Service
metadata:
  name: eval-agent-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: eval-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000